In [2]:
import pandas as pd
jeopardy  = pd.read_csv('jeopardy.csv')

In [3]:
print(jeopardy.head(5))
jeopardy.columns = jeopardy.columns.str.replace(' ','')
jeopardy.columns

   Show Number    Air Date      Round                         Category  Value  \
0         4680  2004-12-31  Jeopardy!                          HISTORY   $200
1         4680  2004-12-31  Jeopardy!  ESPN's TOP 10 ALL-TIME ATHLETES   $200
2         4680  2004-12-31  Jeopardy!      EVERYBODY TALKS ABOUT IT...   $200
3         4680  2004-12-31  Jeopardy!                 THE COMPANY LINE   $200
4         4680  2004-12-31  Jeopardy!              EPITAPHS & TRIBUTES   $200

                                            Question      Answer
0  For the last 8 years of his life, Galileo was ...  Copernicus
1  No. 2: 1912 Olympian; football star at Carlisl...  Jim Thorpe
2  The city of Yuma in this state has a record av...     Arizona
3  In 1963, live on "The Art Linkletter Show", th...  McDonald's
4  Signer of the Dec. of Indep., framer of the Co...  John Adams

Index(['ShowNumber', 'AirDate', 'Round', 'Category', 'Value', 'Question',
       'Answer'],
      dtype='object')

In [4]:
jeopardy['clean_answer'] = jeopardy.Answer.str.lower().str.replace('\W',' ')
jeopardy['clean_question'] = jeopardy.Question.str.lower().str.replace('\W',' ')

In [5]:
def value_normalize(value):
    clean_value = value.replace('$','')
    if clean_value.isdigit():
        return int(clean_value)
    else:
        return int(0)
jeopardy['clean_value'] = jeopardy.Value.apply(value_normalize)

In [6]:
datetime = pd.to_datetime(jeopardy.AirDate)
datetime

0       2004-12-31
1       2004-12-31
2       2004-12-31
3       2004-12-31
4       2004-12-31
5       2004-12-31
6       2004-12-31
7       2004-12-31
8       2004-12-31
9       2004-12-31
10      2004-12-31
11      2004-12-31
12      2004-12-31
13      2004-12-31
14      2004-12-31
15      2004-12-31
16      2004-12-31
17      2004-12-31
18      2004-12-31
19      2004-12-31
20      2004-12-31
21      2004-12-31
22      2004-12-31
23      2004-12-31
24      2004-12-31
25      2004-12-31
26      2004-12-31
27      2004-12-31
28      2004-12-31
29      2004-12-31
           ...
19969   2009-05-14
19970   2009-05-14
19971   2009-05-14
19972   2009-05-14
19973   2009-05-14
19974   2009-05-14
19975   2009-05-14
19976   2009-05-14
19977   2009-05-14
19978   2009-05-14
19979   2009-05-14
19980   2009-05-14
19981   2009-05-14
19982   2009-05-14
19983   2009-05-14
19984   2009-05-14
19985   2009-05-14
19986   2009-05-14
19987   2009-05-14
19988   2000-03-14
19989   2000-03-14
19990   2000-03-14
19991   2000-03-14
19992   2000-03-14
19993   2000-03-14
19994   2000-03-14
19995   2000-03-14
19996   2000-03-14
19997   2000-03-14
19998   2000-03-14
Name: AirDate, Length: 19999, dtype: datetime64[ns]

In [7]:
def match_counts(row):
    split_answer = row['clean_answer'].split()
    split_question = row['clean_question'].split()
    match_count = 0
    if 'the' in split_answer:
        split_answer.remove('the')
    if len(split_answer) == 0:
        return 0
    for value in split_answer:
        if value in split_question:
            match_count +=1
    return match_count/len(split_answer)
jeopardy['answer_in_question'] = jeopardy.apply(match_counts,
                                               axis =1)

In [8]:
jeopardy.answer_in_question.mean()

0.06294645581984949

In [9]:
jeopardy

,ShowNumber,AirDate,Round,Category,Value,Question,Answer,clean_answer,clean_question,clean_value,answer_in_question
0,4680,2004-12-31,Jeopardy!,HISTORY,$200,"For the last 8 years of his life, Galileo was ...",Copernicus,copernicus,for the last 8 years of his life galileo was ...,200,0.000000
1,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$200,No. 2: 1912 Olympian; football star at Carlisl...,Jim Thorpe,jim thorpe,no 2 1912 olympian football star at carlisl...,200,0.000000
2,4680,2004-12-31,Jeopardy!,EVERYBODY TALKS ABOUT IT...,$200,The city of Yuma in this state has a record av...,Arizona,arizona,the city of yuma in this state has a record av...,200,0.000000
3,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$200,"In 1963, live on ""The Art Linkletter Show"", th...",McDonald's,mcdonald s,in 1963 live on the art linkletter show th...,200,0.000000
4,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,$200,"Signer of the Dec. of Indep., framer of the Co...",John Adams,john adams,signer of the dec of indep framer of the co...,200,0.000000
5,4680,2004-12-31,Jeopardy!,3-LETTER WORDS,$200,"In the title of an Aesop fable, this insect sh...",the ant,the ant,in the title of an aesop fable this insect sh...,200,0.000000
6,4680,2004-12-31,Jeopardy!,HISTORY,$400,Built in 312 B.C. to link Rome & the South of ...,the Appian Way,the appian way,built in 312 b c to link rome the south of ...,400,0.000000
7,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$400,"No. 8: 30 steals for the Birmingham Barons; 2,...",Michael Jordan,michael jordan,no 8 30 steals for the birmingham barons 2 ...,400,0.000000
8,4680,2004-12-31,Jeopardy!,EVERYBODY TALKS ABOUT IT...,$400,"In the winter of 1971-72, a record 1,122 inche...",Washington,washington,in the winter of 1971 72 a record 1 122 inche...,400,0.000000
9,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$400,This housewares store was named for the packag...,Crate & Barrel,crate barrel,this housewares store was named for the packag...,400,0.000000
10,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,$400,"""And away we go""",Jackie Gleason,jackie gleason,and away we go,400,0.000000
11,4680,2004-12-31,Jeopardy!,3-LETTER WORDS,$400,Cows regurgitate this from the first stomach t...,the cud,the cud,cows regurgitate this from the first stomach t...,400,0.000000
12,4680,2004-12-31,Jeopardy!,HISTORY,$600,In 1000 Rajaraja I of the Cholas battled to ta...,Ceylon (or Sri Lanka),ceylon or sri lanka,in 1000 rajaraja i of the cholas battled to ta...,600,0.000000
13,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$600,"No. 1: Lettered in hoops, football & lacrosse ...",Jim Brown,jim brown,no 1 lettered in hoops football lacrosse ...,600,0.000000
14,4680,2004-12-31,Jeopardy!,EVERYBODY TALKS ABOUT IT...,$600,"On June 28, 1994 the nat'l weather service beg...",the UV index,the uv index,on june 28 1994 the nat l weather service beg...,600,0.500000
15,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$600,"This company's Accutron watch, introduced in 1...",Bulova,bulova,this company s accutron watch introduced in 1...,600,0.000000
16,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,$600,"Outlaw: ""Murdered by a traitor and a coward wh...",Jesse James,jesse james,outlaw murdered by a traitor and a coward wh...,600,0.000000
17,4680,2004-12-31,Jeopardy!,3-LETTER WORDS,$600,"A small demon, or a mischievous child (who mig...",imp,imp,a small demon or a mischievous child who mig...,600,0.000000
18,4680,2004-12-31,Jeopardy!,HISTORY,$800,Karl led the first of these Marxist organizati...,the International,the international,karl led the first of these marxist organizati...,800,0.000000
19,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$800,No. 10: FB/LB for Columbia U. in the 1920s; MV...,(Lou) Gehrig,lou gehrig,no 10 fb lb for columbia u in the 1920s mv...,800,0.000000
20,4680,2004-12-31,Jeopardy!,EVERYBODY TALKS ABOUT IT...,$800,Africa's lowest temperature was 11 degrees bel...,Morocco,morocco,africa s lowest temperature was 11 degrees bel...,800,0.000000
21,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$800,Edward Teller & this man partnered in 1898 to ...,(Paul) Bonwit,paul bonwit,edward teller this man partnered in 1898 to ...,800,0.000000
22,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,"$2,000","1939 Oscar winner: ""...you are a credit to you...",Hattie McDaniel (for her role in Gone with the...,hattie mcdaniel for her role in gone with the...,1939 oscar winner you are a credit to you...,0,0.000000
23,4680,2004-12-31,Jeopardy!,3-LETTER WORDS,$800,"In geologic time one of these, shorter than an...",era,era,in geologic time one of these shorter than an...,800,0.000000
24,4680,2004-12-31,Jeopardy!,HISTORY,$1000,This Asian political party was founded in 1885...,the Congress Party,the congress party,this asian political party was founded in 1885...,1000,0.500000
25,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$1000,No. 5: Only center to lead the NBA in assists;...,(Wilt) Chamberlain,wilt chamberlain,no 5 only center to lead the nba in assists ...,1000,0.000000
26,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$1000,"The Kirschner brothers, Don & Bill, named this...",K2,k2,the kirschner brothers don bill named this...,1000,0.000000
27,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,$1000,"Revolutionary War hero: ""His spirit is in Verm...",Ethan Allen,ethan allen,revolutionary war hero his spirit is in verm...,1000,0.000000
28,4680,2004-12-31,Jeopardy!,3-LETTER WORDS,$1000,"A single layer of paper, or to perform one's c...",ply,ply,a single layer of paper or to perform one s c...,1000,0.000000
29,4680,2004-12-31,Double Jeopardy!,DR. SEUSS AT THE MULTIPLEX,$400,"<a href=""http://www.j-archive.com/media/2004-1...",Horton,horton,a href http www j archive com media 2004 1...,400,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
19969,5694,2009-05-14,Double Jeopardy!,AMERICAN HISTORY,$1200,In 1960 the last of these locomotives was reti...,steam engines,steam engines,in 1960 the last of these locomotives was reti...,1200,0.000000
19970,5694,2009-05-14,Double Jeopardy!,"MIND YOUR SHAKESPEARE ""P""s & ""Q""s",$1200,"Kate: ""if I be waspish, best beware my sting"";...",Petruchio,petruchio,kate if i be waspish best beware my sting ...,1200,0.000000
19971,5694,2009-05-14,Double Jeopardy!,ALMA MATERS,"$1,500",This private college in Northern California bo...,Stanford University,stanford university,this private college in northern california bo...,0,0.000000
19972,5694,2009-05-14,Double Jeopardy!,ACTRESSES,$1200,"She voiced Princess Pea in ""The Tale of Desper...",Emma Watson,emma watson,she voiced princess pea in the tale of desper...,1200,0.000000
19973,5694,2009-05-14,Double Jeopardy!,2-LETTER WORDS,$1200,It's the name of the long-awaited new White Ho...,Bo,bo,it s the name of the long awaited new white ho...,1200,0.000000
19974,5694,2009-05-14,Double Jeopardy!,ANGELS & DEMONS,$1200,"Langdon in ""Angels & Demons"" is looking for <a...",an antimatter bomb,an antimatter bomb,langdon in angels demons is looking for a...,1200,0.333333
19975,5694,2009-05-14,Double Jeopardy!,AMERICAN HISTORY,$1600,In the 1600s most of New York State was occupi...,the Iroquois,the iroquois,in the 1600s most of new york state was occupi...,1600,0.000000
19976,5694,2009-05-14,Double Jeopardy!,"MIND YOUR SHAKESPEARE ""P""s & ""Q""s",$1600,Marina's dad (need a hint? he rules Tyre),Pericles,pericles,marina s dad need a hint he rules tyre,1600,0.000000
19977,5694,2009-05-14,Double Jeopardy!,ALMA MATERS,$1600,Presidential kids are welcome at this New Orle...,Tulane,tulane,presidential kids are welcome at this new orle...,1600,0.000000
19978,5694,2009-05-14,Double Jeopardy!,ACTRESSES,$1600,She didn't vamp it up & did a bella job as Em ...,Kristen Stewart,kristen stewart,she didn t vamp it up did a bella job as em ...,1600,0.000000
19979,5694,2009-05-14,Double Jeopardy!,2-LETTER WORDS,$1600,Third syllable intoned by the giant who smells...,fo,fo,third syllable intoned by the giant who smells...,1600,0.000000
19980,5694,2009-05-14,Double Jeopardy!,ANGELS & DEMONS,$1600,"Much of ""Angels & Demons"" takes place at one o...",a conclave,a conclave,much of angels demons takes place at one o...,1600,0.500000
19981,5694,2009-05-14,Double Jeopardy!,AMERICAN HISTORY,"$1,200",In 1899 Secretary of State John Hay proclaimed...,open-door policy,open door policy,in 1899 secretary of state john hay proclaimed...,0,0.333333
19982,5694,2009-05-14,Double Jeopardy!,"MIND YOUR SHAKESPEARE ""P""s & ""Q""s",$2000,"Fruity surname of Peter in ""A Midsummer Night'...",Quince,quince,fruity surname of peter in a midsummer night ...,2000,0.000000
19983,5694,2009-05-14,Double Jeopardy!,ALMA MATERS,$2000,"Quincy Jones, Kevin Eubanks & Branford Marsali...",Berklee,berklee,quincy jones kevin eubanks branford marsali...,2000,0.000000
19984,5694,2009-05-14,Double Jeopardy!,ACTRESSES,$2000,"In 2009 she returned to being ""Fast & Furious""...",Michelle Rodriguez,michelle rodriguez,in 2009 she returned to being fast furious ...,2000,0.000000
19985,5694,2009-05-14,Double Jeopardy!,2-LETTER WORDS,$2000,"The book of Genesis says this ancient city ""of...",Ur,ur,the book of genesis says this ancient city of...,2000,0.000000
19986,5694,2009-05-14,Double Jeopardy!,ANGELS & DEMONS,$2000,"""Habakkuk and the Angel"" is one of a series of...",Bernini,bernini,habakkuk and the angel is one of a series of...,2000,0.000000
19987,5694,2009-05-14,Final Jeopardy!,SCIENCE TERMS,None,"In medieval England, it meant the smallest uni...",atom,atom,in medieval england it meant the smallest uni...,0,0.000000
19988,3582,2000-03-14,Jeopardy!,U.S. GEOGRAPHY,$100,This Texas city is the largest in the U.S. to ...,Houston (Lee Brown),houston lee brown,this texas city is the largest in the u s to ...,100,0.000000
19989,3582,2000-03-14,Jeopardy!,POP MUSIC PAIRINGS,$100,...& the Crickets,Buddy Holly,buddy holly,the crickets,100,0.000000
19990,3582,2000-03-14,Jeopardy!,HISTORIC PEOPLE,$100,In the 990s this son of Erik the Red brought C...,Leif Ericson,leif ericson,in the 990s this son of erik the red brought c...,100,0.000000
19991,3582,2000-03-14,Jeopardy!,1998 QUOTATIONS,$100,"Concerning a failed Windows 98 demonstration, ...",Bill Gates,bill gates,concerning a failed windows 98 demonstration ...,100,0.000000
19992,3582,2000-03-14,Jeopardy!,LLAMA-RAMA,$100,"This llama product is used to make hats, blank...",Wool,wool,this llama product is used to make hats blank...,100,0.000000
19993,3582,2000-03-14,Jeopardy!,DING DONG,$100,In 1967 this company introduced its chocolate-...,Hostess,hostess,in 1967 this company introduced its chocolate ...,100,0.000000
19994,3582,2000-03-14,Jeopardy!,U.S. GEOGRAPHY,$200,"Of 8, 12 or 18, the number of U.S. states that...",18,18,of 8 12 or 18 the number of u s states that...,200,1.000000
19995,3582,2000-03-14,Jeopardy!,POP MUSIC PAIRINGS,$200,...& the New Power Generation,Prince,prince,the new power generation,200,0.000000
19996,3582,2000-03-14,Jeopardy!,HISTORIC PEOPLE,$200,In 1589 he was appointed professor of mathemat...,Galileo,galileo,in 1589 he was appointed professor of mathemat...,200,0.000000
19997,3582,2000-03-14,Jeopardy!,1998 QUOTATIONS,$200,"Before the grand jury she said, ""I'm really so...",Monica Lewinsky,monica lewinsky,before the grand jury she said i m really so...,200,0.000000
19998,3582,2000-03-14,Jeopardy!,LLAMA-RAMA,$200,Llamas are the heftiest South American members...,Camels,camels,llamas are the heftiest south american members...,200,0.000000

In [10]:

question_overlap = []
terms_used = set()

jeopardy = jeopardy.sort_values("AirDate",ascending = True)

for i, row in jeopardy.iterrows():
        split_question = row["clean_question"].split(" ")
        split_question = [q for q in split_question if len(q) > 5]
        match_count = 0
        for word in split_question:
            if word in terms_used:
                match_count += 1
        for word in split_question:
            terms_used.add(word)
        if len(split_question) > 0:
            match_count /= len(split_question)
        question_overlap.append(match_count)
jeopardy["question_overlap"] = question_overlap

jeopardy["question_overlap"].mean()

0.7197989717809739

In [19]:
def separate_values(row):
    if row.clean_value > 800:
        value = 1
    else:
        value = 0
    return value
jeopardy['high_value'] = jeopardy.apply(separate_values, axis =1)
def count(word):
    low_count=0
    high_count = 0
    for index, row in jeopardy.iterrows():
        clean_question = row.clean_question.split(" ")
        if word in clean_question:
            if row.high_value == 1:
                high_count +=1
            else:
                low_count +=1
    return high_count, low_count
observed_expected = list()
comparison_terms = list(terms_used)[:5]
for item in comparison_terms:
    high_low_count =count(item)
    observed_expected.append(high_low_count)
print(observed_expected)

[(2, 3), (0, 1), (1, 0), (0, 2), (1, 0)]

In [22]:
from scipy.stats import chisquare
high_value_count = (jeopardy.high_value==1).sum()
low_value_count = (jeopardy.high_value==0).sum()
chi_squared =list()
for item in observed_expected:
    total = item.sum()
    total_prop = total/jeopardy.shape[0]
    expected_high_rows = total_prop*high_value_count
    expected_low_rows = total_prop*low_value_count
    observed = [item[0],item[1]]
    expected = [expected_high_rows,expected_low_rows]
    result = chisquare(observed,expected)
    chi_squared.append(result)
print(chi_squared)

[Power_divergenceResult(statistic=0.6134279937303524, pvalue=0.4335000217020267), Power_divergenceResult(statistic=0.3308710986890265, pvalue=0.565146603267378), Power_divergenceResult(statistic=3.022325020112631, pvalue=0.08212564786568953), Power_divergenceResult(statistic=0.661742197378053, pvalue=0.4159455550913672), Power_divergenceResult(statistic=3.022325020112631, pvalue=0.08212564786568953)]